name: Demo Issue Events
run-name: Issue event 🚀

on:
  workflow_dispatch:
  issues:
    types:
      - opened

jobs:
  print_context:
    runs-on: ubuntu-latest
    steps:
      - env:
          EVENT_CONTEXT: ${{ toJSON(github.event) }}
        run: |
          # echo $EVENT_CONTEXT | jq '.'
          python ${{ github.workspace }}/owasp-agent-client/main.py

