name: Demo Issue Events
run-name: Issue event 🚀

on:
  workflow_dispatch:
  issues:
    types:
      - opened

jobs:
  call_agent:
    runs-on: ubuntu-latest
    steps:
      - env:
          EVENT_CONTEXT: ${{ toJSON(github.event) }}
        run: |
          ls -lah ${{ github.workspace }}
          echo "."
          ls -lah ${{ github.workspace }}/owasp-agent-client
          echo "."
          cat ${{ github.workspace }}/owasp-agent-client/main.py