name: Demo Issue Events
run-name: Issue event 🚀

on:
  workflow_dispatch:
  issues:
    types:
      - opened

jobs:
  call_agent:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - env:
          EVENT_CONTEXT: ${{ toJSON(github.event) }}
          REPOSITORY_VARS: ${{ toJSON(vars) }}
        run: |
          echo $REPOSITORY_VARS | jq .
      - env:
          EVENT_CONTEXT: ${{ toJSON(github.event) }}
          REPOSITORY_VARS: ${{ toJSON(vars) }}
        run: |
          python ${{ github.workspace }}/owasp-agent-client/main.py
